defaultVaultConnection:
   enabled: true
   address: "http://vault.vault.svc.cluster.local:8200"
   skipTLSVerify: false

controller:
   manager:
      clientCache:
         persistenceModel: direct-encrypted
         storageEncryption:
            enabled: true
            mount: kubernetes-auth
            keyName: vso-client-cache
            transitMount: operator-transit
            kubernetes:
               role: auth-role-operator
               serviceAccount: operator-transit-auth-sa
