apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: vault-secrets-operator
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: v0.10.0 # Replace with the Vault Secret Operator version you'd like to install or upgrade to
      helm:
        valueFiles: 
        - $values/vault-secrets-operator-values.yaml
    - repoURL: 'https://github.com/wartoz/vault.git'
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: vault-secrets-operator-system

